apiVersion: v1
kind: ConfigMap
metadata:
  name: revcart-config
  namespace: revcart
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CLOUD_CONSUL_HOST: "consul"
  SPRING_CLOUD_CONSUL_PORT: "8500"
  SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS: "true"

  # MySQL
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_OPTS: "useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_USERNAME: "root"

  # Redis
  SPRING_REDIS_HOST: "redis"
  SPRING_REDIS_PORT: "6379"

  # MongoDB
  SPRING_DATA_MONGODB_HOST: "mongodb"
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_USERNAME: "admin"

  # Mail
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
